---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmqcluster
spec:
  image: rabbitmq:3.8.9-management
  replicas: 3
  service:
    type: LoadBalancer # ClusterIP | LoadBalancer
  resources:
    requests:
      # cpu: 3000m
      memory: 512Mi
    # limits:
    #   cpu: 1000m
    #   memory: 2Gi
  rabbitmq:
    additionalConfig: |
                  log.console.level = info
                  channel_max = 700
                  default_user= guest 
                  default_pass = guest
                  default_user_tags.administrator = true
    additionalPlugins:
      - rabbitmq_top
      - rabbitmq_shovel
  persistence:
    storageClassName: standard
    storage: 5Gi
