---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmqcluster
spec:
  image: rabbitmq:3.10.2-management
  replicas: 1
  service:
    type: LoadBalancer # ClusterIP | LoadBalancer
  resources:
    requests:
      # cpu: 3000m
      memory: 512Mi
    # limits:
    #   cpu: 1000m
    #   memory: 2Gi
  rabbitmq:
    additionalConfig: |
                  log.console.level = info
                  channel_max = 700
                  default_user= guest 
                  default_pass = guest
                  default_user_tags.administrator = true
    advancedConfig: | 
                [
                  {rabbitmq_shovel,
                    [ {shovels, [ {my_first_shovel,
                                    [ {source,
                                        [ {protocol, amqp091},
                                          {uris, [ "amqp://default:default@host1.domain/my_vhost" ]},
                                          {declarations, [ {'exchange.declare',
                                                              [ {exchange, <<"my_fanout">>},
                                                                {type, <<"fanout">>},
                                                                durable
                                                              ]},
                                                            {'queue.declare',
                                                              [{arguments,
                                                                  [{<<"x-message-ttl">>, long, 60000}]}]},
                                                            {'queue.bind',
                                                              [ {exchange, <<"my_fanout">>},
                                                                {queue,    <<>>}
                                                              ]}
                                                            ]},
                                          {queue, <<>>},
                                          {prefetch_count, 10}
                                        ]},
                                      {destination,
                                        [ {protocol, amqp091},
                                          {uris, ["amqp://"]},
                                          {declarations, [ {'exchange.declare',
                                                              [ {exchange, <<"my_direct">>},
                                                                {type, <<"direct">>},
                                                                durable
                                                              ]}
                                                          ]},
                                          {publish_properties, [ {delivery_mode, 2} ]},
                                          {add_forward_headers, true},
                                          {publish_fields, [ {exchange, <<"my_direct">>},
                                                            {routing_key, <<"from_shovel">>}
                                                            ]}
                                            ]},
                                      {ack_mode, on_confirm},
                                      {reconnect_delay, 5}
                                    ]}
                                ]}
                    ]},
                  ].
    additionalPlugins:
      - rabbitmq_top
      - rabbitmq_shovel
#                   additionalConfig:
#                     description: Modify to add to the rabbitmq.conf file in addition to default configurations set by the operator. Modifying this property on an existing RabbitmqCluster will trigger a StatefulSet rolling restart and will cause rabbitmq downtime. For more information on this config, see https://www.rabbitmq.com/configure.html#config-file
#                     maxLength: 2000
#                     type: string
#                   additionalPlugins:
#                     description: 'List of plugins to enable in addition to essential plugins: rabbitmq_management, rabbitmq_prometheus, and rabbitmq_peer_discovery_k8s.'
#                     items:
#                       description: A Plugin to enable on the RabbitmqCluster.
#                       maxLength: 100
#                       pattern: ^\w+$
#                       type: string
#                     maxItems: 100
#                     type: array
#                   advancedConfig:
#                     description: Specify any rabbitmq advanced.config configurations to apply to the cluster. For more information on advanced config, see https://www.rabbitmq.com/configure.html#advanced-config-file
#                     maxLength: 100000
#                     type: string
#                   envConfig:
#                     description: Modify to add to the rabbitmq-env.conf file. Modifying this property on an existing RabbitmqCluster will trigger a StatefulSet rolling restart and will cause rabbitmq downtime. For more information on env config, see https://www.rabbitmq.com/man/rabbitmq-env.conf.5.html
#                     maxLength: 100000
#                     type: string
  persistence:
    storageClassName: local-path
    storage: 5Gi
